// register action types
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_REQUEST_SUCCESS = "REGISTER_REQUEST_SUCCESS";
export const REGISTER_REQUEST_ERROR = "REGISTER_REQUEST_ERROR";

// login action types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_REQUEST_SUCCESS = "LOGIN_REQUEST_SUCCESS";
export const LOGIN_REQUEST_ERROR = "LOGIN_REQUEST_ERROR";
export const SET_USER_LOGIN = "SET_USER_LOGIN";
export const SET_USER_LOGOUT = "SET_USER_LOGOUT";
